# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# wgs84.py
# Created on: 2023-06-15 19:58:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
env.workplace = r"C:\Users\25830\OneDrive - oganneson\桌面\学习\python学习\python_learning\arc\python_arcpy\Precipitation"

fls = arcpy.ListFiles()
for fl in fls:
    print fl
    output1 = r"D:\yaoganguochengshuju\output"
    output2 = output1 + fl [-10 : -4]

# Process: ASCII 转栅格
    arcpy.ASCIIToRaster_conversion(fl, output2, "INTEGER")

# Process: 定义投影
    arcpy.DefineProjection_management(output2, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

